@Library(value='kids-first/aws-infra-jenkins-shared-libraries', changelog=false) _
ecs_service_type_1_standard {
    projectName            = "d3b-disease-express"
    orgFullName            = "d3b-center"
    org                    = "d3b"
    account                = "chopd3bPrd"
    environments           = "prd"
    docker_image_type      = "debian"
    entrypoint_command     = "java_standard_jar"
    deploy_scripts_version = "master"
    container_port         = "9000"
    health_check_path      = "/"
    domain_external        = "d3b.io"
    friendly_dns_name      = "disease-express-api"
    vcpu_container         = "2048"
    memory_container       = "4096"
    vcpu_task              = "2048"
    memory_task            = "4096"
    internal_app           = "false"
    quick_deploy           = "true"
}
